export const Book_List = [
  {
    id: "b1",
    title: "Ali ve Ece",
    description: "Hippoterapi Merkezinde",
    image: "/images/books/ali_ve_ece.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b2",
    title: "Dersimiz Futbol",
    description:
      "Futbol Eğitiminde Sağlikli Beslenme, Antrenman ve Oyun Kurallari",
    image: "/images/books/dersimiz_futbol.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b3",
    title: "Helvaci",
    description: "Kültür, Tarih, Coğrafya",
    image: "/images/books/helvaci.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b4",
    title: "Aliağa Kuş Cenneti",
    description: "ve Güzelhisar Deltasi",
    image: "/images/books/aliaga_kus_cenneti.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b5",
    title: "Myrina ve Gryneion-4",
    description: "Desc Text",
    image: "/images/books/myrina4.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b6",
    title: "Myrina ve Gryneion-3",
    description: "Desc Text",
    image: "/images/books/myrina3.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b7",
    title: "Tisna-I",
    description: "TİSNA ANTİK KENTİ’NDE İLK ARAŞTIRMALAR VE GÖZLEMLER",
    image: "/images/books/tisna1.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b8",
    title: "Yörükler ve Derici Yörükleri Tarihi",
    description: "Desc Text",
    image: "/images/books/yörükler_ve_derici.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b9",
    title: "Aliağa ve Çevresi",
    description: "Desc Text",
    image: "/images/books/aliaga_ve_cevresi.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },

  {
    id: "b10",
    title: "Aliağa Çocuk Oyunları",
    description: "Desc Text",
    image: "/images/books/aliaga_cocuk_oyunlari.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b11",
    title: "Aliağa Coğrafya Atlası",
    description: "Desc Text",
    image: "/images/books/aliaga_cografya_atlasi.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b12",
    title: "Aliağa ve Çevresindeki Antik Kentler ",
    description: "Desc Text",
    image: "/images/books/aliaga_ve_cevresi.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b13",
    title: "Seyyahların İzinde Aliağa ve Çevresi",
    description: "Desc Text",
    image: "/images/books/seyyahlarin_izinde.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b14",
    title: "16. Yüzyılda Güzelhisar",
    description: "Desc Text",
    image: "/images/books/tapu_tahrir_defter.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b15",
    title: "Myrina ve Gryneion-2",
    description: "Desc Text",
    image: "/images/books/myrina_ve_gryneion2.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },

  {
    id: "b16",
    title: "I. Aliağa Sempozyum Bildirileri",
    description: "Desc Text",
    image: "/images/books/aliaga_sempozyumu.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b17",
    title: "Aliağa Tarihi",
    description: "İlk Çağ'dan 21. Yüzyıla",
    image: "/images/books/aliaga_tarihi.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b18",
    title: "Myrina ve Gryneion-1",
    description: "Desc Text",
    image: "/images/books/myrina_ve_gryneion.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b19",
    title: "Güzelhisar",
    description: "Aliağa Çevresi ile Birlikte",
    image: "/images/books/aliaga_ve_guzelhisar.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
  {
    id: "b20",
    title: "Aliağa’nın Antik Kentleri",
    description: "Desc Text",
    image: "/images/books/antik_kentler5.png",
    writer: "Berrat Aktaş",
    coordinator: "Dummy",
    totalPage: "DummyNumber",
    publishDay: "Dummy",
    isbnNumber: "Dummy",
    paperOwner: "Dummy",
    place: "",
    graphicDesign: "",
    bg: false,
  },
];
